### ISSUE TITLE
Make unit tests run in parallel in GitHub Actions

### ISSUE THREAD

**Issue by alex-titarenko** [NotesHubApp/git-essentials#10]
https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
https://stackoverflow.com/questions/66025220/paired-values-in-github-actions-matrix

**Comment by alex-titarenko** [comment]
```yaml
on: push
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm install-ci-test
    - uses:
  publish:
    needs: [test]
    steps:
    - uses: actions/checkout@v3
```
